locals {
	emptyprimaryregion = var.primaryregion == "" ? var.region : var.primaryregion
    	primaryregion = var.local_data_guard_enabled ? local.emptyprimaryregion : var.region
	standbyregion = var.remote_data_guard_enabled ? var.standbyregion : var.region
	johannesburg="${var.region == "af-johannesburg-1" ? "ocid1.image.oc1.af-johannesburg-1.aaaaaaaaoljxu5yrpjhs7o5hra2u6wh3qyefba4do37wspeljr23emcugrja" : ""}"
	chuncheon="${var.region == "ap-chuncheon-1" ? "ocid1.image.oc1.ap-chuncheon-1.aaaaaaaa6jdpov5eqfoxox4oeguhjgegsn2up5rclfznppwjuo5e6ydonalq" : ""}"
	hyderabad="${var.region == "ap-hyderabad-1" ? "ocid1.image.oc1.ap-hyderabad-1.aaaaaaaa2wcejwlvzqplhtrsaanu2tykrsubgqrb2i5o475ccl3gtwxsusrq" : ""}"
	melbourne="${var.region == "ap-melbourne-1" ? "ocid1.image.oc1.ap-melbourne-1.aaaaaaaactkh4ar64tln7uwxeiggizoemlufkxzy6wvst66xx2kx2oveietq" : ""}"
	mumbai="${var.region == "ap-mumbai-1" ? "ocid1.image.oc1.ap-mumbai-1.aaaaaaaaa5wytrdj2dwrrcyts2nwxymaifwbnqbrlnem475kgwjliorrhzlq" : ""}"
	osaka="${var.region == "ap-osaka-1" ? "ocid1.image.oc1.ap-osaka-1.aaaaaaaawmxntsigxjtu2z7n7jwefdqqfvnpe7ltvrh3ymbv3kog2l6anaaa" : ""}"
	seoul="${var.region == "ap-seoul-1" ? "ocid1.image.oc1.ap-seoul-1.aaaaaaaaw5aixrk2jhhj2cfkehczyttgp7die342evjzdidiqian3vkcgn6a" : ""}"
	singapore="${var.region == "ap-singapore-1" ? "ocid1.image.oc1.ap-singapore-1.aaaaaaaalnwa2qv3iuj4l22spse2mtjb2r4layvypturuqlklntdfkyts6bq" : ""}"
	sydney="${var.region == "ap-sydney-1" ? "ocid1.image.oc1.ap-sydney-1.aaaaaaaacb7rrnqplygbry6jxfds3rdrkugsloeyrlies4zijga6p75idsxq" : ""}"
	tokyo="${var.region == "ap-tokyo-1" ? "ocid1.image.oc1.ap-tokyo-1.aaaaaaaaub2gikosfetvtrgwa6cqwhtt25ukkiaogbpsfiyiayus6puifm3q" : ""}"
	montreal="${var.region == "ca-montreal-1" ? "ocid1.image.oc1.ca-montreal-1.aaaaaaaawahf5vyul5ixkvc5xcn4bevv6urzz3qk3dscs36hcuj2ufr2y3la" : ""}"
	toronto="${var.region == "ca-toronto-1" ? "ocid1.image.oc1.ca-toronto-1.aaaaaaaanzxg2lycvtpzgobswpp3kht3byzc4kduvbuzks7u65r5zlyrzdaq" : ""}"
	amsterdam="${var.region == "eu-amsterdam-1" ? "ocid1.image.oc1.eu-amsterdam-1.aaaaaaaahr3su6ec6jaoysv26pjr5mtvcjt253nk3t5au7ku2ujbs2piyjca" : ""}"
	frankfurt="${var.region == "eu-frankfurt-1" ? "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaajlfyitbkkb7xd763rzkduqc3v4biryi6ebdvg7x5fo6arm7tv6hq" : ""}"
	madrid="${var.region == "eu-madrid-1" ? "ocid1.image.oc1.eu-madrid-1.aaaaaaaazmviegp5jztelok6xc3ln66e6dqf7cemeb2njytmsifb3l4v6iaa" : ""}"
	marseille="${var.region == "eu-marseille-1" ? "ocid1.image.oc1.eu-marseille-1.aaaaaaaa5gaf7aiegl2dhlp3lrzhjnqblhkdlb5whjy243xyim2r2c3gezbq" : ""}"
	milan="${var.region == "eu-milan-1" ? "ocid1.image.oc1.eu-milan-1.aaaaaaaauhqi5wjnr5nda2budtubgxxy4vc5sue4364sgw3iqrsjitpsj2pa" : ""}"
	paris="${var.region == "eu-paris-1" ? "ocid1.image.oc1.eu-paris-1.aaaaaaaapp4pl2hbuq4gyohamtgrwjmwcv5t2ktlwij4vilx2grwex5q2iwq" : ""}"
	stockholm="${var.region == "eu-stockholm-1" ? "ocid1.image.oc1.eu-stockholm-1.aaaaaaaagciot5tiengpjxlkvzzjci732dlvwy6rhmx5tabjt7eue4ugh2oa" : ""}"
	zurich="${var.region == "eu-zurich-1" ? "ocid1.image.oc1.eu-zurich-1.aaaaaaaabi3zwcnzegvgawpm3xqxafia24gp7xo33f7jsmmtujle4yo5wtxq" : ""}"
	jerusalem="${var.region == "il-jerusalem-1" ? "ocid1.image.oc1.il-jerusalem-1.aaaaaaaayoxcer4n7vbxl3harkauz6dvj5wnilbeab5ee6ivtrfl4kdqd3xq" : ""}"
	abudhabi="${var.region == "me-abudhabi-1" ? "ocid1.image.oc1.me-abudhabi-1.aaaaaaaaghllcudftv7stnbu3jj6zuzufzwtwkrfayp3vi563ujjonby45fq" : ""}"
	dubai="${var.region == "me-dubai-1" ? "ocid1.image.oc1.me-dubai-1.aaaaaaaatsvtkq2mfmfkb4sy7luv6bkofrxkfh4qgvu5pexkp5gnzpllw4ya" : ""}"
	jeddah="${var.region == "me-jeddah-1" ? "ocid1.image.oc1.me-jeddah-1.aaaaaaaa7wblipbzuhjrnptnov2u4mpuujp4jh53iycfi3lnldwiq4mq3lka" : ""}"
	queretaro="${var.region == "mx-queretaro-1" ? "ocid1.image.oc1.mx-queretaro-1.aaaaaaaanrjnij47r7oo6d26yqfhhel35wdhrowvm4f3542uwbawqchzo7wq" : ""}"
	santiago="${var.region == "sa-santiago-1" ? "ocid1.image.oc1.sa-santiago-1.aaaaaaaaontbvhh5ebaeaa4ix44xveqvmv2awl6b4to7ilkiefxtjlhrkewq" : ""}"
	saopaulo="${var.region == "sa-saopaulo-1" ? "ocid1.image.oc1.sa-saopaulo-1.aaaaaaaapwotlpqctjugilokte7y7dk5iimnusvygtlsxdfcaif26lzvek7a" : ""}"
	vinhedo="${var.region == "sa-vinhedo-1" ? "ocid1.image.oc1.sa-vinhedo-1.aaaaaaaagjshcki7cfmqwsjg4msn2mn4h7hjxqja2rngx2hdd3fb6nolms2q" : ""}"
	cardiff="${var.region == "uk-cardiff-1" ? "ocid1.image.oc1.uk-cardiff-1.aaaaaaaayynf27faurcgwtedzwoybnkbmaqeceaglt3yr6luraonuyfryfvq" : ""}"
	london="${var.region == "uk-london-1" ? "ocid1.image.oc1.uk-london-1.aaaaaaaaxhkwp7kvbinuf2zje4cja7hwazn2jpiz6pkzljibweqzvp6lmr3q" : ""}"
	ashburn="${var.region == "us-ashburn-1" ? "ocid1.image.oc1.iad.aaaaaaaazavxtitjiojkyivwwb72pn2vcvnoxirpgkhf26i2ku4egieknkxq" : ""}"
	chicago="${var.region == "us-chicago-1" ? "ocid1.image.oc1.us-chicago-1.aaaaaaaaluzqhjcqpvkep2cl62kgjtbruh2c7qwzcsrwaxczntgay66qm2ma" : ""}"
	phoenix="${var.region == "us-phoenix-1" ? "ocid1.image.oc1.phx.aaaaaaaakol6el3peuinalmnd3ksfr7qyvfnqw7pvma4b6pjkf6hev7bfiqa" : ""}"
	sanjose="${var.region == "us-sanjose-1" ? "ocid1.image.oc1.us-sanjose-1.aaaaaaaa7nkg2bsmlyrrc6d6ak5xlwjpaq5gyr4zsg2dfdwsfmag3sumabuq" : ""}"
	region1 = "${coalesce(local.chuncheon,local.hyderabad,local.melbourne,local.mumbai,local.osaka ,local.seoul,local.sydney,local.tokyo,local.toronto,local.amsterdam,local.frankfurt,local.zurich,local.dubai ,local.jeddah,local.santiago,local.saopaulo,local.vinhedo,local.cardiff,local.london,local.ashburn,local.phoenix,local.sanjose)}"
}
